[logic]
mode = 'Normal'
assured_weapon = false
bell_in_shop = false
pouch_in_shop = false
boots_in_shop = false
super_items = false
minigames_excluded = false
skip_trials = false
bow_of_light_in_castle = false
swordless_mode = false
