## Modifications to logic.
[logic]
## Ravio will give out the Bracelet at the very start of the game
# start_with_bracelet = false
## Place items using logic that potentially requires glitches to complete
# glitched_logic = false
## Disables lamp requirement for dark areas.
# dont_require_lamp_for_darkness = false
## Exclude all minigames (Cucco Ranch, both Rupee Rushes, Hyrule Hotfoot, Treacherous Tower, and Octoball Derby)
# minigames_excluded = true
## Requires seller's golden bee for Bee Badge check.
# require_golden_bee_for_sale = false
## Allows keys to be placed in an order that can lead to softlocks.
# unsafe_key_placement = true

## Excludes certain locations from having progression items.
[exclude]
## Use the names from the spoiler log.
# [exclude.Lorule]
# 'Death Mountain' = [
#     'Treacherous Tower (Advanced 1)',
#     'Treacherous Tower (Advanced 2)',
# ]
